apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eva-seqcol
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wwwint.ebi.ac.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eva-seqcol
            port:
              number: 8081